# jekyll config
# vim: set ft=yaml et ts=2 sts=2 :

# Configuration
permalink: "/:categories/:year/:month/:day/:title/"
markdown: kramdown
hilighter: pygments
lsi: false
exclude: [.gitignore, _config.yml, _libraries, Makefile, tidy.log, old]
gems:
  - jekyll-sitemap

# Custom variables
title: "番茄女王的花园"
url: "https://tomato.github.io"
keywords: ""

# Author information
author:
  name: "Queen Tomato"
  mail: "190543745@qq.com"
  github: "tomato"
  keybase: "tomato"

# Disqus
disqus:
  shortname: "tomato"

